
paths:
  /api/productos/:
    get:
      summary: Obtiene todos los productos
      tags:
        - Products
      responses:
        "200":
          description: Los productos fueron obtenidos OK desde la DB
        "500":
          description: Error interno del servidor
    post:
      summary: Crea un producto
      tags:
        - Products
      responses:
        "201":
          description: Producto creado
        "500":
          description: Error interno del servidor